src/blog.Web/Pages/Account/Login.cshtml.cs
using blog.Users;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Account.Settings;
using Volo.Abp.Account.Web;
using Volo.Abp.Account.Web.Pages.Account;
using Volo.Abp.Auditing;
using Volo.Abp.Identity;
using Volo.Abp.Identity.AspNetCore;
using Volo.Abp.Security.Claims;
using Volo.Abp.Settings;
using Volo.Abp.Validation;
using IdentityUser = Volo.Abp.Identity.IdentityUser;
using SignInResult = Microsoft.AspNetCore.Identity.SignInResult;

namespace blog.Web.Pages.Account
{
    public class LoginModel : AccountPageModel
    {
        [HiddenInput]
        [BindProperty(SupportsGet = true)]
        public string ReturnUrl { get; set; }

        [HiddenInput]
        [BindProperty(SupportsGet = true)]
        public string ReturnUrlHash { get; set; }

        [BindProperty]
        public LoginInputModel LoginInput { get; set; }

        public bool EnableLocalLogin { get; set; }

        //TODO: Why there is an ExternalProviders if only the VisibleExternalProviders is used.
        public IEnumerable<ExternalProviderModel> ExternalProviders { get; set; }
        public IEnumerable<ExternalProviderModel> VisibleExternalProviders => ExternalProviders.Where(x => !String.IsNullOrWhiteSpace(x.DisplayName));

        public bool IsExternalLoginOnly => EnableLocalLogin == false && ExternalProviders?.Count() == 1;
        public string ExternalLoginScheme => IsExternalLoginOnly ? ExternalProviders?.SingleOrDefault()?.AuthenticationScheme : null;

        protected IAuthenticationSchemeProvider SchemeProvider { get; }
        protected AbpAccountOptions AccountOptions { get; }

        public bool ShowCancelButton { get; set; }



        public LoginModel(
            IAuthenticationSchemeProvider schemeProvider,
            IOptions<AbpAccountOptions> accountOptions)
        {
            SchemeProvider = schemeProvider;
            AccountOptions = accountOptions.Value;
        }

        public virtual async Task<IActionResult> OnGetAsync()
        {
            LoginInput = new LoginInputModel();

            ExternalProviders = await GetExternalProviders();

            EnableLocalLogin = await SettingProvider.IsTrueAsync(AccountSettingNames.EnableLocalLogin);

            if (IsExternalLoginOnly)
            {
                //return await ExternalLogin(vm.ExternalLoginScheme, returnUrl);
                throw new NotImplementedException();
            }

            return Page();
        }

        public virtual async Task<IActionResult> OnPostAsync(string action)
        {
            await CheckLocalLoginAsync();

            ValidateModel();

            ExternalProviders = await GetExternalProviders();

            EnableLocalLogin = await SettingProvider.IsTrueAsync(AccountSettingNames.EnableLocalLogin);

            await ReplaceEmailToUsernameOfInputIfNeeds();

            var result = await SignInManager.PasswordSignInAsync(
                LoginInput.UserNameOrEmailAddress,
                LoginInput.Password,
                LoginInput.RememberMe,
                true
            );

            await IdentitySecurityLogManager.SaveAsync(new IdentitySecurityLogContext()
            {
                Identity = IdentitySecurityLogIdentityConsts.Identity,
                Action = result.ToIdentitySecurityLogAction(),
                UserName = LoginInput.UserNameOrEmailAddress
            });

            if (result.RequiresTwoFactor)
            {
                return await TwoFactorLoginResultAsync();
            }

            if (result.IsLockedOut)
            {
                Alerts.Warning(L["UserLockedOutMessage"]);
                return Page();
            }

            if (result.IsNotAllowed)
            {
                Alerts.Warning(L["LoginIsNotAllowed"]);
                return Page();
            }

            if (!result.Succeeded)
            {
                Alerts.Danger(L["InvalidUserNameOrPassword"]);
                return Page();
            }

            //TODO: Find a way of getting user's id from the logged in user and do not query it again like that!
            var user = await UserManager.FindByNameAsync(LoginInput.UserNameOrEmailAddress) ??
                       await UserManager.FindByEmailAsync(LoginInput.UserNameOrEmailAddress);

            Debug.Assert(user != null, nameof(user) + " != null");

            //return RedirectSafely(ReturnUrl, ReturnUrlHash);
            return RedirectToPage("/Home/Homepage");
        }

        protected virtual Task<IActionResult> TwoFactorLoginResultAsync()
        {
            throw new NotImplementedException();
        }

        protected virtual async Task<List<ExternalProviderModel>> GetExternalProviders()
        {
            var schemes = await SchemeProvider.GetAllSchemesAsync();

            return schemes
                .Where(x => x.DisplayName != null || x.Name.Equals(AccountOptions.WindowsAuthenticationSchemeName, StringComparison.OrdinalIgnoreCase))
                .Select(x => new ExternalProviderModel
                {
                    DisplayName = x.DisplayName,
                    AuthenticationScheme = x.Name
                })
                .ToList();
        }

        //External login
        public virtual async Task<IActionResult> OnPostExternalLoginAsync(string provider)
        {
            var redirectUrl = Url.Page("./Login", pageHandler: "ExternalLoginCallback", values: new { ReturnUrl = "/", ReturnUrlHash });
            var properties = SignInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            properties.Items["scheme"] = provider;
            return await Task.FromResult(Challenge(properties, provider));
        }

        //External login callback
        public virtual async Task<IActionResult> OnGetExternalLoginCallbackAsync(string returnUrl = "", string returnUrlHash = "", string remoteError = null)
        {

            if (remoteError != null)
            {
                Logger.LogWarning($"External login callback error: {remoteError}");
                return RedirectToPage("./Login");
            }

            var loginInfo = await SignInManager.GetExternalLoginInfoAsync();
            if (loginInfo == null)
            {
                Logger.LogWarning("External login info is not available");
                return RedirectToPage("./Login");
            }

            var result = await SignInManager.ExternalLoginSignInAsync(
                loginInfo.LoginProvider,
                loginInfo.ProviderKey,
                isPersistent: false,
                bypassTwoFactor: true
            );

            if (!result.Succeeded)
            {
                await IdentitySecurityLogManager.SaveAsync(new IdentitySecurityLogContext()
                {
                    Identity = IdentitySecurityLogIdentityConsts.IdentityExternal,
                    Action = "Login" + result
                });
            }

            if (result.IsLockedOut)
            {
                throw new UserFriendlyException("Cannot proceed because user is locked out!");
            }

            if (result.Succeeded)
            {
                return RedirectSafely(returnUrl, returnUrlHash);
            }

            //TODO: Handle other cases for result!
            // Get the information about the user from the external login provider
            var externalLoginInfo = await SignInManager.GetExternalLoginInfoAsync();
            if (externalLoginInfo == null)
            {
                throw new ApplicationException("Error loading external login information during confirmation.");
            }

            var user = await CreateExternalUserAsync(externalLoginInfo);

            await SignInManager.SignInAsync(user, false);
            await IdentitySecurityLogManager.SaveAsync(new IdentitySecurityLogContext()
            {
                Identity = IdentitySecurityLogIdentityConsts.IdentityExternal,
                Action = result.ToIdentitySecurityLogAction(),
                UserName = user.Name
            });

            return RedirectSafely(returnUrl, returnUrlHash);
        }

        private static bool IsEmailRetrievedFromExternalLogin(ExternalLoginInfo externalLoginInfo)
        {
            return externalLoginInfo.Principal.FindFirstValue(AbpClaimTypes.Email) != null;
        }

        protected virtual async Task<IdentityUser> CreateExternalUserAsync(ExternalLoginInfo info)
        {
            var emailAddress = info.Principal.FindFirstValue(ClaimTypes.Email);

            var user = new IdentityUser(GuidGenerator.Create(), emailAddress, emailAddress, CurrentTenant.Id);

            CheckIdentityErrors(await UserManager.CreateAsync(user));
            CheckIdentityErrors(await UserManager.SetEmailAsync(user, emailAddress));
            CheckIdentityErrors(await UserManager.AddLoginAsync(user, info));
            CheckIdentityErrors(await UserManager.AddDefaultRolesAsync(user));

            return user;
        }

        protected virtual async Task ReplaceEmailToUsernameOfInputIfNeeds()
        {
            if (!ValidationHelper.IsValidEmailAddress(LoginInput.UserNameOrEmailAddress))
            {
                return;
            }

            var userByUsername = await UserManager.FindByNameAsync(LoginInput.UserNameOrEmailAddress);
            if (userByUsername != null)
            {
                return;
            }

            var userByEmail = await UserManager.FindByEmailAsync(LoginInput.UserNameOrEmailAddress);
            if (userByEmail == null)
            {
                return;
            }

src/blog.Web/Pages/Account/ManageProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using blog.Account;
using blog.Permissions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Identity;

namespace blog.Web.Pages.Account
{
    public class ManageProfileModel : PageModel
    {

        private readonly IAccountAppService appService;
        private readonly IAuthorizationService authorization;
        private readonly Identity.IdentityRoleAppSerivce roleAppSerivce;

        public ManageProfileModel(IAccountAppService appService, IAuthorizationService authorization, Identity.IdentityRoleAppSerivce roleAppSerivce)
        {
            this.appService = appService;
            this.authorization = authorization;
            this.roleAppSerivce = roleAppSerivce;
        }

        [BindProperty(SupportsGet = true)]
        public IdentityUserDto userDto { get; set; }

        [BindProperty]
        public string newPassword { get; set; } = String.Empty;

        [BindProperty]
        public string newPasswordConfirm { get; set; } = String.Empty;

        public List<blog.Identity.IdentityRoleDto> RoleLists { get; set; }

        [BindProperty]
        public string UserRole { get; set; }

        [BindProperty]
        public string UpdateUserRole { get; set; }
        public async Task<IActionResult> OnGetAsync(Guid userId)
        {
            var result = await authorization.IsGrantedAsync(blogPermissions.User.ManageUser);
            //if(result)
            //{
                RoleLists = await roleAppSerivce.GetAllListAsync2();
                //Get userRole
                UserRole = (await roleAppSerivce.GetUserRole(userId)).Name;
                userDto = await appService.FindByIdAsync(userId);
                userDto.Id = userId;
                return Page();
            //}
            //return RedirectToPage("/Error/AccessDenied", new { errorMesseage = "You don't have permission of Manage Profile!" });
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(!newPassword.IsNullOrEmpty())
            {
                if (!newPasswordConfirm.Equals(newPassword)) return await this.OnGetAsync(userDto.Id);
                await appService.UpdateProfileWithPassword(userDto, newPassword);
            }
            else
            {
                await appService.UpdateProfile(userDto);
                //nếu userRole khác lúc trước thì update userRole
                if (!UserRole.Equals(UpdateUserRole)) await roleAppSerivce.UpdateUserRole(userDto.Id, UpdateUserRole);
            }
            return await this.OnGetAsync(userDto.Id);
        }

    }
}

src/blog.Web/Pages/Account/Login.cshtml
@page
@{
    Layout = "";
}
@using Microsoft.AspNetCore.Mvc.Localization
@using Volo.Abp.Account.Localization
@using Volo.Abp.Account.Settings
@using Volo.Abp.Settings
@model blog.Web.Pages.Account.LoginModel
@inject IHtmlLocalizer<AccountResource> L
@inject Volo.Abp.Settings.ISettingProvider SettingProvider

    <abp-style-bundle>
        <abp-style src="/css/login.css" />
    </abp-style-bundle>
<div class="login-page">
    <div class="form">
        <form class="register-form">
            <input type="text" placeholder="name" asp-controller="Administration" asp-action="Register" />
            <input type="password" placeholder="password" />
            <input type="text" placeholder="email address" />
            <button type="submit">create</button>
            <p class="message">Already registered? <a href="#">Sign In</a></p>
        </form>
        <form class="login-form" method="post">
            <input type="text" placeholder="username" asp-for="LoginInput.UserNameOrEmailAddress" />
            <input type="password" placeholder="password" asp-for="LoginInput.Password" />
            <input type="checkbox" id="rememberMe" style="float: left; width: 5%; margin-right: 10px;margin-top:5px;" asp-for="LoginInput.RememberMe" />
            <label for="rememberMe" style="float:left;font-size:15px;">Remember Me?</label>
            <button type="submit">login</button>
            <span style="color:red;margin-top:10px;font-size:12px;"></span>
            <div style="color:red;margin-top:10px;font-size:12px;"></div>

            <p class="message">Not registered? <a asp-controller="Administration" asp-action="Register">Create an account</a></p>
        </form>
        <form method="post" style="height:50px;">
            <button type="submit" asp-page-handler="ExternalLogin" asp-route-provider="Facebook" style="width:45%;float:left;background-color:#087bea;">
                Facebook
            </button>
            <button type="submit" asp-page-handler="ExternalLogin" asp-route-provider="Google" style="width:45%;float:right;background-color:#cb4236">
                Google
            </button>
        </form>
    </div>
</div>

src/blog.Web/Pages/Account/ManageProfile.cshtml
@page
@model blog.Web.Pages.Account.ManageProfileModel
@{
    ViewData["Title"] = "ManageProfile";
    Layout = "_MyLayout";
}


<div class="container" style="    background-color: white;
        padding: 50px;
        padding-bottom: 20px;
        transform: translateY(10%);
        margin-top: 4%;
        margin-bottom: 14%;
    ">
    <div class="row">
        <div class="col-sm-3">
            <!--left col-->
            <div class="text-center">
                <img src="~/imgs/me.jpg" class="avatar img-circle img-thumbnail" alt="avatar" id="blah">
                <h1 style="font-size: 1.5rem">@Model.userDto.Name</h1>
            </div>

        </div><!--/col-3-->
        <div class="col-sm-9">
            <ul class="nav nav-tabs" style="margin-bottom:30px;">
                <li class="active"><a data-toggle="tab" href="#home">Profile</a></li>
            </ul>

            <div class="tab-content">
                <div class="tab-pane active" id="home">
                    <form class="form" method="post" id="registrationForm" enctype="multipart/form-data">

                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="first_name"><h6>User Name</h6></label>
                                <input type="text" class="form-control" id="first_name" asp-for="@Model.userDto.UserName" placeholder="User Name" >
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-6">
                                <label for="first_name"><h6>Name</h6></label>
                                <input type="text" class="form-control" id="first_name" asp-for="@Model.userDto.Name" placeholder="Name">
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-xs-6">
                                <label for="phone"><h6>Phone Number</h6></label>
                                <input type="text" class="form-control" id="phone" asp-for="@Model.userDto.PhoneNumber" placeholder="Phone number">
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-xs-6">
                                <label for="role"><h6>Roles:</h6></label>
                                <select type="text" class="form-control" id="role" asp-for="UpdateUserRole">
                                    @for (int i = 0; i < @Model.RoleLists.Count(); i++)
                                    {
                                        <option value="@Model.RoleLists[i].Name">@Model.RoleLists[i].Name</option>
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-xs-6">
                                <label for="email"><h6>Email</h6></label>
                                <input type="email" class="form-control" id="email" asp-for="@Model.userDto.Email" placeholder="you@email.com">
                            </div>
                        </div>

                        @*<div class="form-group">

            <div class="col-xs-6">
                <label for="role"><h6>Roles:</h6></label>
                <select type="text" class="form-control" id="role" asp-for="@Model.userDto.RoleName" value="@Model.RoleName">
                    @for (int i = 0; i < roleList.Count; i++)
                    {
                        <option value="@roleList[i].Name">@roleList[i].Name</option>
                    }
                </select>
            </div>
        </div>*@
                        <h4>Change password</h4>
                        <div class="form-group">

                            <div class="col-xs-6">
                                <label for="password"><h6>New password(optional)</h6></label>
                                <input class="form-control" type="password" id="password" asp-for="@Model.newPassword" autocomplete="new-password">
                            </div>
                        </div>

                        <div class="form-group">

                            <div class="col-xs-6">
                                <label for="password2"><h6>Confirm password</h6></label>
                                <input type="password" class="form-control" asp-for="@Model.newPasswordConfirm" id="password2" placeholder="confirm new password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-xs-12">
                                <br>
                                <input type="hidden" asp-for="@Model.userDto.Id" />
                                <input type="hidden" asp-for="@Model.UserRole" />
                                <button class="btn btn btn-success" type="submit"><i class="glyphicon glyphicon-ok-sign"></i> Lưu thay đổi</button>
                                @*@if (ViewBag.IsSuccess != null && ViewBag.IsSuccess == true)
        {
            <span class="text-success">Update Successful!</span>
        }*@
                            </div>
                        </div>
                        <div asp-validation-summary="All" class="text-danger"></div>
                    </form>
                    <hr>
                </div><!--/tab-pane-->
            </div><!--/tab-content-->
        </div><!--/col-9-->
    </div><!--/row-->
</div>