src/blog.Web/Pages/Category/CategoryList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using blog.Categories;
using blog.Category;
using blog.Posts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace blog.Web.Pages.Category
{
    public class CategoryListModel : PageModel
    {
        private readonly ICateAppService categoryService;

        public CategoryListModel(ICateAppService categoryService)
        {
            this.categoryService = categoryService;
        }

        //[BindProperty(SupportsGet = true)]
        public List<CategoryDto> CategoryList { get; set; } = new List<CategoryDto>();

        public List<PostDto> SamePostList { get; set; } = new List<PostDto>();
        
        public async Task<IActionResult> OnGetAsync()
        {
            CategoryList = await categoryService.GetCateList();
            return Page();
        }

    }
}

src/blog.Web/Pages/Category/CreateCategory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using blog.Categories;
using blog.Permissions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace blog.Web.Pages.Category
{
    public class CreateCategoryModel : PageModel
    {
        private readonly ICateAppService categoryService;
        private readonly IAuthorizationService authorization;

        public CreateCategoryModel(ICateAppService categoryService, IAuthorizationService authorization)
        {
            this.categoryService = categoryService;
            this.authorization = authorization;
        }

        public void OnGet()
        {

        }

        [BindProperty]
        public CategoryDto CreateCategoryInput { get; set; }

        public bool flag { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            var result = await authorization.IsGrantedAsync(blogPermissions.Category.CreateCategory);
            if(result)
            {
                flag = await categoryService.CreateCategory(CreateCategoryInput);
                return Page();
            }
            return RedirectToPage("/Error/AccessDenied", new { errorMesseage = "You don't have permission of Create Category!" });
        }
    }
}

src/blog.Web/Pages/Category/UpdateCategory.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using blog.Categories;
using blog.Permissions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace blog.Web.Pages.Category
{
    public class UpdateCategoryModel : PageModel
    {
        private readonly ICateAppService categoryService;
        private readonly IAuthorizationService authorization;

        public UpdateCategoryModel(ICateAppService categoryService, IAuthorizationService authorization)
        {
            this.categoryService = categoryService;
            this.authorization = authorization;
        }

        [BindProperty(SupportsGet = true)]
        public CategoryDto SpecificCategoryDto { get; set; } = new CategoryDto();

        public async Task<IActionResult> OnGetAsync(Guid cateId)
        {
            var result = await authorization.IsGrantedAsync(blogPermissions.Category.CreateCategory);
            if(result)
            {
                SpecificCategoryDto.Name = await categoryService.GetCategoryName(cateId);
                SpecificCategoryDto.Id = cateId;

                return Page();
            }    

            else
            {
                return RedirectToPage("/Error/AccessDenied", new { errorMesseage = "You don't have permission of Update Category!" } );
            }                
            
        }

        public bool flag { get; set; }

        public async Task<IActionResult> OnPostUpdateCategoryAsync()
        {
            flag = await categoryService.UpdateCategory(SpecificCategoryDto);
            return await this.OnGetAsync(SpecificCategoryDto.Id);
        }

        public async Task<IActionResult> OnPostDeleteCategoryAsync()
        {
            flag = await categoryService.DeleteCategory(SpecificCategoryDto.Id);
            return RedirectToPage("/Category/CategoryList");
        }
    }
}

src/blog.Web/Pages/Category/CategoryList.cshtml
@page
@model blog.Web.Pages.Category.CategoryListModel
@inject blog.Category.CategoryService cateService;
@using blog.Category;

@{
    ViewData["Title"] = "CategoryList";
    Layout = "_MyLayout";
    var categories = Model.CategoryList;
}


@section scripts
{
    <abp-script src="/Pages/Category/CategoryList.js" />
}

@section style
{
    <abp-style src="/css/listpost.css" />
}


<div class="container-fluid" style="background-color:#E9FAE0;position:relative;margin-top:8%;padding: 5px 60px;">
    <img src="https://miro.medium.com/max/3008/1*Z326IB1LmJtbpMwg2LkRdg.gif" style="margin-top: 5%; width: 100%;" />
    <a asp-page="/Post/PostList" class="text-danger" font-size="15px;">See List Posts</a>
    @for (int i = 0; i < categories.Count; i++)
    {
        <h1 style="text-decoration: underline; color: #557C24; font-weight:800;text-align:center;font-size: 60px;
">
            @categories[i].Name
        </h1>
        @*@if (signInManager.IsSignedIn(User) && User.HasClaim("Update Category", "true"))
            {
                <a asp-controller="Category" asp-action="UpdateCategory" asp-route-cateId="@categories[i].Id ">Update Category</a>
            }*@

        <a asp-page="/Category/UpdateCategory" asp-route-cateId="@categories[i].Id ">Update Category</a>

        var listOfPostSameCategory = await cateService.GetPostInSameCategory(categories[i].Id);
        if (listOfPostSameCategory.Count == 0)
        {
            <h4>No Post have added to this Category!</h4>
        }
        <ul class="blog-list" style="list-style-type:none;margin-bottom:5%;">
            @for (int j = 0; j < listOfPostSameCategory.Count; j++)
            {
                var photoPath = "";
                if (listOfPostSameCategory[j].PhotoPath == null) photoPath = "/imgs/default.jpg";
                else
                {
                    photoPath = "/imgs/" + listOfPostSameCategory[j].PhotoPath;
                }
                <li>
                    <div class="post">
                        <a asp-page="/Post/PostDetail" asp-route-postId="@listOfPostSameCategory[j].Id">
                            <img src="@photoPath" alt="No image" width="70%" onmouseover="bigImg(this)" onmouseout="normalImg(this)" />
                        </a>
                        <a asp-controller="Post" asp-action="PostDetail" asp-route-postId="@listOfPostSameCategory[j].Id">

                            <h1 style="font-size:25px;font-weight:800" class="postTitle">@listOfPostSameCategory[j].Title</h1>
                        </a>
                        <h4>@listOfPostSameCategory[j].Author</h4>
                        <h5>@listOfPostSameCategory[j].Description<span>... </span><i><a style="font-size:14px;" asp-page="/Post/PostDetail" asp-route-postId="@listOfPostSameCategory[j].Id"> View Details</a></i></h5>
                        <h4>
                            <i>@listOfPostSameCategory[j].CreatedAt</i>
                        </h4>
                        @*@if (signInManager.IsSignedIn(User) && User.HasClaim("Update Post", "true"))
                            {
                                <a asp-controller="Post" asp-action="UpdatePost" asp-route-postId="@listOfPostSameCategory[j].Id" class="text-danger" font-size="15px;">Update Post</a>
                            }*@
                    </div>
                </li>
            }
        </ul>
        <hr width="70%">
    }
</div>

src/blog.Web/Pages/Category/CreateCategory.cshtml
@page
@model blog.Web.Pages.Category.CreateCategoryModel
@{
    ViewData["Title"] = "CreateCategory";
    Layout = "_MyLayout";
}


<div class="container-fluid" style="        background-color: white;
        position: absolute;
        top: 15%;
        padding-bottom: 30px;
        padding-top: 30px;
        padding-left: 60px;
">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            <h1>Create category</h1>
            <br />
            <form asp-page="/Category/CreateCategory" method="post" enctype="multipart/form-data">

                <div class="form-group">
                    <label for="title">Title <span class="require">*</span></label>
                    <input type="text" class="form-control" id="title" asp-for="@Model.CreateCategoryInput.Name" />
                </div>

                <div class="form-group">
                    <p><span class="require">*</span> - required fields</p>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        Create
                    </button>
                    <button class="btn btn-default">
                        Cancel
                    </button>
                    @if (Model.flag == true)
                    {
                        <span class="text-success">Create Successfully!</span>
                    }
                </div>
                <div asp-validation-summary="All" class="text-danger"></div>
            </form>
        </div>

    </div>
</div>

src/blog.Web/Pages/Category/UpdateCategory.cshtml
@page
@model blog.Web.Pages.Category.UpdateCategoryModel
@{
    ViewData["Title"] = "UpdateCategory";
}

@{ 

}

 <div class="container-fluid" style="background-color:white;position: absolute;top: 15%;padding-bottom:30px;padding-top:30px;">
        <div class="row">

            <div class="col-md-8 col-md-offset-2">

                <h1>Update Category</h1>
                <br />
                <form method="post" enctype="multipart/form-data">
                    <input type="hidden" class="form-control" id="title" asp-for="@Model.SpecificCategoryDto.Id"  />
                    <div class="form-group">
                        <label for="title">Title <span class="require">*</span></label>
                        <input type="text" class="form-control" id="title" asp-for="@Model.SpecificCategoryDto.Name" />
                    </div>

                    <div class="form-group">
                        <p><span class="require">*</span> - required fields</p>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary" asp-page-handler="UpdateCategory">
                            Update
                        </button>

                        <button class="btn btn-default">
                            Cancel
                        </button>
                        @if (Model.flag)
                        {
                            <span class="text-success">Update Successfully!</span>
                        }
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                </form>

                <form method="post">
                    <input type="hidden" class="form-control" id="title" name="cateId" asp-for="@Model.SpecificCategoryDto.Id" />
                    <button type="submit" class="btn btn-danger" asp-page-handler="DeleteCategory">
                        Delete
                    </button>
                </form>
            </div>

        </div>
    </div>