src/blog.Web/Pages/Post/CreatePost.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using blog.Categories;
using blog.Permissions;
using blog.Posts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace blog.Web.Pages.Post
{
    public class CreatePostModel : PageModel
    {
        private readonly IPostAppService postService;
        private readonly ICateAppService cateAppService;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IAuthorizationService authorization;

        public CreatePostModel(IPostAppService postService, ICateAppService cateAppService, IHostingEnvironment hostingEnvironment, IAuthorizationService authorization)
        {
            this.postService = postService;
            this.cateAppService = cateAppService;
            this.hostingEnvironment = hostingEnvironment;
            this.authorization = authorization;
        }

        public async Task<IActionResult> OnGet()
        {
            var result = await authorization.IsGrantedAsync(blogPermissions.Post.CreatePost);
            if(result)
            {
                ListCategory = await cateAppService.GetCateList();
                return Page();
            }
            return RedirectToPage("/Error/AccessDenied", new { errorMesseage = "You don't have permission of Create Post!" });
        }

        [BindProperty]
        public CreateUpdatePostDto postDto { get; set; }

        public List<CategoryDto> ListCategory { get; set; }
        public bool flag { get; set; }
        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (postDto.PhotoFile != null)
                {
                    postDto.PhotoPath = CreatePhoto(postDto.PhotoFile);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Please choose a photo represent for this post.");
                }
                flag = await postService.CreatePost(postDto);
            }
            return await this.OnGet();
        }


        public string CreatePhoto(IFormFile photoPath)
        {
            string uniqueFileName = null;
            uniqueFileName = Guid.NewGuid().ToString() + "_" + photoPath.FileName;
            var filePath = Path.Combine(hostingEnvironment.WebRootPath + "/imgs", uniqueFileName);
            // Use CopyTo() method provided by IFormFile interface to
            // copy the file to wwwroot/images folder
            postDto.PhotoFile.CopyTo(new FileStream(filePath, FileMode.Create));
            return uniqueFileName;
        }
    }
}

src/blog.Web/Pages/Post/PostDetail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using blog.Categories;
using blog.Posts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace blog.Web.Pages.Post
{
    public class PostDetailModel : PageModel
    {
        private readonly IPostAppService postService;
        private readonly ICateAppService cateService;


        public PostDetailModel(IPostAppService postService, ICateAppService cateService)
        {
            this.postService = postService;
            this.cateService = cateService;
        }

        [BindProperty]
        public Guid PostDetailInput { get; set; }

        public List<PostDto> PostList { get; set; } = new List<PostDto>();
        public PostDto SpecificPost { get; set; }

        public string CategoryName { get; set; }
        public async Task<IActionResult> OnGetAsync(Guid postId)
        {
            PostList = await postService.GetPosts();
            SpecificPost = await postService.GetSepecificPost(postId);
            CategoryName = await cateService.GetCategoryName(SpecificPost.CategoryId);
            return Page();
        }
    }
}

src/blog.Web/Pages/Post/PostList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using blog.Posts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace blog.Web.Pages.Post
{
    public class PostListModel : PageModel
    {
        private readonly IPostAppService postService;

        public PostListModel(IPostAppService postService)
        {
            this.postService = postService;
        }

        public List<PostDto> PostList { get; set; } = new List<PostDto>();

        public async Task<IActionResult> OnGetAsync()
        {
            PostList = await postService.GetPosts();
            return Page();
        }
    }
}

src/blog.Web/Pages/Post/UpdatePost.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using blog.Categories;
using blog.Permissions;
using blog.Posts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace blog.Web.Pages.Post
{
    public class UpdatePostModel : PageModel
    {
        private readonly IPostAppService postService;
        private readonly ICateAppService cateService;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly IAuthorizationService authorization;


        public UpdatePostModel(IPostAppService postService, ICateAppService cateService, IHostingEnvironment hostingEnvironment, IAuthorizationService authorization)
        {
            this.postService = postService;
            this.cateService = cateService;
            this.hostingEnvironment = hostingEnvironment;
            this.authorization = authorization;
        }

        [BindProperty(SupportsGet = true)]
        public CreateUpdatePostDto UpdatedPostDto { get; set; } = new CreateUpdatePostDto();

        public List<CategoryDto> CategoryList { get; set; }


        public async Task<IActionResult> OnGetAsync(Guid postId)
        {
            var result = await authorization.IsGrantedAsync(blogPermissions.Post.UpdatePost);
            if(result)
            {
                CategoryList = await cateService.GetCateList();
                UpdatedPostDto = await postService.GetUpdatedPost(postId);
                return Page();
            }
            else
            {
                return RedirectToPage("/Error/AccessDenied", new { errorMesseage = "You don't have permission of Update Post!" });
            }

        }

        public bool flag { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (UpdatedPostDto.PhotoFile != null)
                {
                    uniqueFileName = Guid.NewGuid().ToString() + "_" + UpdatedPostDto.PhotoFile.FileName;
                    var filePath = Path.Combine(hostingEnvironment.WebRootPath + "/imgs", uniqueFileName);

                    UpdatedPostDto.PhotoFile.CopyTo(new FileStream(filePath, FileMode.Create));
                    UpdatedPostDto.PhotoPath = uniqueFileName;
                }
                      
                flag = await postService.UpdatePost(UpdatedPostDto);
            }
            return RedirectToPage("/Post/PostList");
        }

        public async Task<IActionResult> OnPostDeletePostAsync()
        {
            var flag = await postService.DeletePost(UpdatedPostDto.Id);
            return RedirectToPage("/Post/PostList");
        }
    }
}

src/blog.Web/Pages/Post/CreatePost.cshtml
@page
@model blog.Web.Pages.Post.CreatePostModel
@{
    ViewData["Title"] = "CreatePost";
    Layout = "_MyLayout";
    var categories = Model.ListCategory;
}

@section style
{
    <abp-style src="/css/createpost.css" />
}
<div class="container-fluid" style="        background-color: white;
        position: relative;
        margin-top: 8%;
        padding-bottom: 30px;
        padding-top: 30px;
        padding-left: 15%;
">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

            <h1>Create post</h1>
            <br />
            <form method="post" enctype="multipart/form-data">

                <div class="form-group">
                    <label for="title">Title <span class="require">*</span></label>
                    <input type="text" class="form-control" id="title" asp-for="@Model.postDto.Title" />
                </div>

                <div class="form-group">
                    <label for="author">Author <span class="require">*</span></label>
                    <input type="text" class="form-control" id="author" asp-for="@Model.postDto.Author" />
                </div>

                <div class="form-group">
                    <label for="cate">Category <span class="require">*</span></label>
                    <select type="text" class="form-control" id="cate" asp-for="@Model.postDto.CategoryId">
                        @for (int i = 0; i < categories.Count; i++)
                        {
                            <option value="@categories[i].Id">@categories[i].Name</option>
                        }
                    </select>
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <input type="text" class="form-control" id="description" asp-for="@Model.postDto.Description" />
                </div>

                <div class="form-group">
                    <label for="content">Content</label>
                    <textarea rows="5" class="form-control" id="content" asp-for="@Model.postDto.Content"></textarea>
                </div>

                <div class="form-group">
                    <label for="photo">Photo</label>
                    <input type="file" asp-for="@Model.postDto.PhotoFile" multiple />
                </div>

                <div class="form-group">
                    <p><span class="require">*</span> - required fields</p>
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-primary">
                        Create
                    </button>
                    <button class="btn btn-default">
                        Cancel
                    </button>
                    @if (Model.flag)
                    {
                        <span class="text-success">Create Successfully!</span>
                    }
                </div>
                <div asp-validation-summary="All" class="text-danger"></div>
            </form>
        </div>
    </div>
</div>

src/blog.Web/Pages/Post/PostDetail.cshtml
@page
@model blog.Web.Pages.Post.PostDetailModel
@{
    ViewData["Title"] = "PostDetail";

}

@{
    var categoryName = Model.CategoryName;
    var postLists = Model.PostList;
    var spePost = Model.SpecificPost;
    var imgFile = "../imgs/" + spePost.PhotoPath;
}

@section styles
{
    <abp-style src="/css/postdetail.css" />
}

<div class="main container-fluid" style="background-color:white;position:relative;">
    <h5>@categoryName</h5>
    <h2>@spePost.Title</h2>
    <a href="http://ahmetaksungur.com/" class="authorlink" style="padding-bottom:20px;">@spePost.Author</a>
    <content class="pl-0 col-md-7 fl" style="transform: translateX(20px);">
        <img src="@imgFile" style="display:block; margin: auto auto" />
        <p style="margin-top:20px;font-size:21px;">
            @spePost.Content
        </p>

    </content>
    <sidebar class="col-md-5 fl pr-0" style=" transform: translateX(-10px); ">

        <h2>Highlights</h2>
        @for (int i = 0; i < postLists.Count; i++)
        {
            if (postLists[i].Id != spePost.Id && postLists[i].CategoryId == spePost.CategoryId)
            {
                var photoPath = "../imgs/" + postLists[i].PhotoPath;
                <div class="post__card-2">
                    <div class="post__card_-2">
                        <div class="post__card_meta-2" style="padding: 20px;">
                            <a asp-page="/Post/PostDetail" asp-route-postId="@postLists[i].Id" style="color:black;">
                                <p class="post__card_title-2">@postLists[i].Title</p>
                            </a>
                            <p class="post__card_alttitle-2">@postLists[i].Author</p>
                        </div>
                        <div class="post__card__image-2" style="background-image: url('@photoPath');">
                        </div>
                    </div>
                </div>
            }
        }
</div>

src/blog.Web/Pages/Post/PostList.cshtml
@page
@model blog.Web.Pages.Post.PostListModel
@{
    ViewData["Title"] = "List of Post";
    Layout = "_MyLayout";
    var posts = Model.PostList;
}

@section style
{
    <abp-style src="/css/listpost.css" />
}

<div class="container-fluid" style="position:relative">
    <ul class="blog-list" style="margin-top: 10%; list-style-type:none ">
        @for (int i = 0; i < Model.PostList.Count(); i++)
        {
            var photoPath = "";
            if (posts[i].PhotoPath == null) photoPath = "/imgs/default.jpg";
            else
            {
                photoPath = "/imgs/" + posts[i].PhotoPath;
            }
            <li>
                <div class="post">
                    <img src="@photoPath" alt="No image" width="100%" />
                    <h1 style="font-size:25px;font-weight:800">
                        <a asp-page="/Post/PostDetail" asp-route-postId="@posts[i].Id">
                            @posts[i].Title
                        </a>
                    </h1>
                    <a asp-page="/Post/UpdatePost" asp-route-postId="@posts[i].Id">Update Post</a>
                    <h4>@posts[i].Author</h4>
                    <h5>@posts[i].Description<span>... </span><i><a style="font-size:14px;" asp-page="/Post/PostDetail" asp-route-postId="@posts[i].Id" > View Details</a></i></h5>
                    <h4>
                        <i>@posts[i].CreatedAt</i>
                    </h4>
                    @*@if (User.IsInRole("Admin"))
                    {
                        <a asp-controller="Post" asp-action="UpdatePost" asp-route-postId="@posts[i].Id" class="text-danger" font-size="15px;">Update Post</a>
                    }*@
                </div>
            </li>
        }
    </ul>
</div>

src/blog.Web/Pages/Post/UpdatePost.cshtml
@page
@model blog.Web.Pages.Post.UpdatePostModel
@{
    ViewData["Title"] = "UpdatePost";
    var categories = Model.CategoryList;
}

    <div class="container-fluid" style="background-color:white;position: absolute;top: 15%;padding-bottom:30px;padding-top:30px;">
        <div class="row">

            <div class="col-md-8 col-md-offset-2">

                <h1>Update post</h1>
                <br />
                <form method="post" enctype="multipart/form-data">
                    <input type="hidden" asp-for="@Model.UpdatedPostDto.Id" />
                    <input type="hidden" asp-for="@Model.UpdatedPostDto.CreationTime" />
                    <input type="hidden" asp-for="@Model.UpdatedPostDto.CreatedAt" />
                    <div class="form-group">
                        <label for="title">Title <span class="require">*</span></label>
                        <input type="text" class="form-control" id="title" asp-for="@Model.UpdatedPostDto.Title" />
                    </div>

                    <div class="form-group">
                        <label for="author">Author <span class="require">*</span></label>
                        <input type="text" class="form-control" id="author" asp-for="@Model.UpdatedPostDto.Author" />
                    </div>

                    <div class="form-group">
                        <label for="cate">Category <span class="require">*</span></label>
                        <select type="text" class="form-control" id="cate" asp-for="@Model.UpdatedPostDto.CategoryId">
                            @for (int i = 0; i < categories.Count; i++)
                            {
                                <option value="@categories[i].Id">@categories[i].Name</option>
                            }
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="description">Description</label>
                        <input type="text" class="form-control" id="description" asp-for="@Model.UpdatedPostDto.Description" />
                    </div>

                    <div class="form-group">
                        <label for="content">Content</label>
                        <textarea rows="5" class="form-control" id="content" asp-for="@Model.UpdatedPostDto.Content"></textarea>
                    </div>

                    <h4><b>Change Photo(Optionals)...</b></h4>
                    <div class="form-group">
                        <label for="photo">Photo</label>
                        <input type="file" asp-for="@Model.UpdatedPostDto.PhotoFile" multiple />
                    </div>

                    <div class="form-group">
                        <p><span class="require">*</span> - required fields</p>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>
                        <button type="reset" class="btn btn-default">
                            Cancel
                        </button>
                        @if (Model.flag)
                        {
                            <span class="text-success">Update Successfully!</span>
                        }
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                </form>

                <form method="post">
                    <input type="hidden" asp-for="@Model.UpdatedPostDto.Id" />
                    <button type="submit" class="btn btn-danger" asp-page-handler="DeletePost">
                        Delete
                    </button>
                </form>

            </div>

        </div>
    </div>